// packages/playground/solid/src/App.tsx
import { createEffect, createSignal, onMount } from 'solid-js'

const App = () => {
  const [count, setCount] = createSignal(0)

  createEffect(() => {
    console.log('Count is now', count())
  })

  onMount(() => {
    console.log('Solid App mounted')
  })

  return (
    <div>
      <h1>Solid Playground</h1>
      <p>
        Count:
        {count()}
      </p>
      <button onClick={() => setCount(count() + 1)}>
        Increment
      </button>
    </div>
  )
}

export default App

// packages/playground/svelte/src/App.svelte
<script>
  let count = $state(0)

  function increment() {
    count += 1
  }

  $effect(() => {
    console.log(`The count is now ${count}`)
  })
</script>

<main>
  <h1>Svelte Playground</h1>
  <button on:click={increment}>
    Count: {count}
  </button>
</main>

<style>
  main {
    padding: 1rem;
  }
</style>
